export class ModelSummarizer {
    constructor() {
        this.supportedFormats = ['onnx', 'tflite', 'coreml', 'tensorrt', 'openvino'];
        this.taskPatterns = {
            classification: { outputs: /^(logits|scores|probabilities|output|classes)$/i, shapes: [/^\[.*,\s*1000\]$/], ops: ['Softmax', 'ArgMax', 'GlobalAveragePool'] },
            detection: { outputs: /^(boxes|detections|output|bboxes|anchors)$/i, shapes: [/^\[.*,\s*4\]$/], ops: ['NonMaxSuppression', 'NMS', 'Resize', 'Gather'] }
        };
    }

    summarize(model) {
        if (!model) return this._getEmptySummary();
        let graphs = null;
        if (model && model._modules && model._modules.length > 0) { graphs = model._modules; }
        else if (model && model.modules && model.modules.length > 0) { graphs = model.modules; }
        else if (model && model.graphs && model.graphs.length > 0) { graphs = model.graphs; }
        if (!graphs || graphs.length === 0) return this._getEmptySummary();
        const graph = graphs[0];
        const summary = { modelName: this._extractModelName(model), format: this._detectFormat(model), inputs: this._extractInputs(graph), outputs: this._extractOutputs(graph), operators: this._analyzeOperators(graph), taskGuess: this._guessTaskWithConfidence(model, graph), usage: this._extractUsage(model), application: this._extractApplication(model), quantization: this._checkQuantizationWithProvenance(graph), runtimeHints: this._suggestRuntimes(model), metadata: this._extractMetadata(model), complexity: this._estimateComplexity(graph) };
        try { if (typeof globalThis !== 'undefined') globalThis.__MODEL_SUMMARY__ = summary; } catch (e) {}
        return summary;
    }

    _getEmptySummary() { return { modelName: 'No Model Loaded', format: 'unknown', inputs: [], outputs: [], operators: { total: 0, types: {}, topOps: [] }, taskGuess: { value: 'unknown', provenance: 'heuristic', confidence: 0.0 }, quantization: { isQuantized: false, precision: 'fp32', provenance: 'graph_scan', confidence: 1.0 }, runtimeHints: ['cpu'], metadata: {}, complexity: { parameters: 0, flops: 0, size: 0 } }; }

    _extractModelName(model) { if (model.name) return model.name; if (model._metadata?.name) return model._metadata.name; if (model.metadata?.name) return model.metadata.name; return 'Unknown Model'; }
    _detectFormat(model) { try { if (model._format) return model._format.toLowerCase(); if (model.format) return model.format.toLowerCase(); if (model.identifier) { const ext = model.identifier.split('.').pop()?.toLowerCase(); const map = { 'onnx':'onnx','pb':'tensorflow','tflite':'tflite','mlmodel':'coreml' }; return map[ext] || ext; } } catch (e) {} return 'unknown'; }
    _extractInputs(graph) { const inputs = []; const actualInputs = Array.isArray(graph) ? graph : (graph.inputs || graph.input || graph._inputs || graph._input || []); if (actualInputs) { for (const input of actualInputs) { const shape = this._parseShape(input); const dtype = this._parseDtype(input); const domain = this._guessDomain(input); const netronRaw = this._buildNetronRaw(input, shape, dtype); inputs.push({ name: input.name || 'input', shape, dtype, domain, netronRaw, provenance: domain === 'unknown' ? 'inferred' : 'model', confidence: domain === 'unknown' ? 0.5 : 1.0 }); } } return inputs; }
    _extractOutputs(graph) { const outputs = []; const actualOutputs = Array.isArray(graph) ? graph : (graph.outputs || graph.output || graph._outputs || graph._output || []); if (actualOutputs) { for (const output of actualOutputs) { const shape = this._parseShape(output); const dtype = this._parseDtype(output); const semantics = this._guessSemantics(output); const netronRaw = this._buildNetronRaw(output, shape, dtype); outputs.push({ name: output.name || 'output', shape, dtype, semantics, netronRaw, provenance: semantics === 'unknown' ? 'inferred' : 'model', confidence: semantics === 'unknown' ? 0.5 : 1.0 }); } } return outputs; }
    _buildNetronRaw(tensor, shape, dtype) { try { const s = tensor && typeof tensor.toString === 'function' ? tensor.toString() : null; if (s && !s.startsWith('[object')) return s; } catch {} if (dtype && Array.isArray(shape) && shape.length > 0) { const shapeStr = shape.map((d) => (d === undefined || d === null) ? '?' : String(d)).join(','); return `${dtype}[${shapeStr}]`; } if (tensor && tensor.name) return tensor.name; try { return JSON.stringify(tensor, (k, v) => (typeof v === 'function' ? undefined : v)); } catch { return String(tensor); } }
    _analyzeOperators(graph) { const opCounts = {}; let total = 0; if (graph.nodes) { for (const node of graph.nodes) { const opType = node.type || node.op_type || 'unknown'; opCounts[opType] = (opCounts[opType] || 0) + 1; total++; } } const topOps = Object.entries(opCounts).sort(([,a], [,b]) => b - a).slice(0,10).map(([op,count]) => ({op,count})); return { total, types: opCounts, topOps }; }
    _guessTaskWithConfidence(model, graph) { const features = { modelName: (model.identifier || model.name || '').toLowerCase(), format: this._detectFormat(model), inputs: this._extractInputs(graph), outputs: this._extractOutputs(graph), operators: this._analyzeOperators(graph) }; let bestGuess = { value: 'unknown', confidence: 0, provenance: 'heuristic' }; try { const byName = this._analyzeByName(features.modelName); if (byName && byName.confidence > bestGuess.confidence) bestGuess = { ...byName, provenance: 'heuristic' }; const byIO = this._analyzeByInputOutput(features.inputs, features.outputs); if (byIO && byIO.confidence > bestGuess.confidence) bestGuess = { ...byIO, provenance: 'heuristic' }; } catch (e) {} return bestGuess; }
    _analyzeByName(modelName) { const patterns = [{pattern:/(classification|classifier|cls)/i,task:'classification',confidence:0.8},{pattern:/(detection|detect|yolo|ssd|rcnn)/i,task:'detection',confidence:0.9}]; for (const p of patterns) { if (p.pattern.test(modelName)) return {value:p.task,confidence:p.confidence}; } return null; }
    _analyzeByInputOutput(inputs, outputs) { if (!inputs || !outputs) return null; const inputShapes = inputs.map(i=>i.shape); const outputShapes = outputs.map(o=>o.shape); const hasImageInput = inputShapes.some(s=>s.length>=3 && (s[1]===3 || s[3]===3)); if (hasImageInput) { if (outputs.length===1 && outputShapes[0].length<=2) { const lastDim = outputShapes[0][outputShapes[0].length-1]; if (typeof lastDim === 'number' && lastDim>1 && lastDim<=10000) return {value:'classification',confidence:0.8}; } const hasBboxOutput = outputShapes.some(s=>s.length>=2 && s[s.length-1]===4); if (hasBboxOutput) return {value:'detection',confidence:0.9}; } return null; }
    _parseShape(tensor) { const shapeExtractors = [ () => { if (Array.isArray(tensor.value) && tensor.value[0]?.type?.shape?.dimensions) return tensor.value[0].type.shape.dimensions.map(this._normalizeDimension.bind(this)); if (tensor.arguments && tensor.arguments[0]?.type?.shape?.dimensions) return tensor.arguments[0].type.shape.dimensions.map(this._normalizeDimension.bind(this)); return null; }, () => tensor.type?.shape?.dimensions?.map(this._normalizeDimension.bind(this)), () => { if (Array.isArray(tensor.shape)) return tensor.shape.map(this._normalizeDimension.bind(this)); return null; }, () => { const s = tensor.toString?.() || ''; const m = s.match(/\[([0-9,?]+)\]/); if (m) return m[1].split(',').map(d=>d.trim()==='?'?'?':parseInt(d,10)); return null; } ]; for (const ex of shapeExtractors) { try { const r = ex(); if (r && Array.isArray(r) && r.length>0) return r.map(d=>this._normalizeDimension(d)); } catch { continue; } } return []; }
    _normalizeDimension(dim) { if (typeof dim==='number') return dim; if (typeof dim==='object') { if (dim.size!==undefined) return dim.size; if (dim.value!==undefined) return dim.value; } if (typeof dim==='string') { const p=parseInt(dim,10); return isNaN(p) ? '?' : p; } return dim===null||dim===undefined ? '?' : dim; }
    _parseDtype(tensor) { const dtypeExtractors = [ () => { if (tensor.arguments && tensor.arguments[0]?.type?.dataType) return tensor.arguments[0].type.dataType; return null; }, () => { const s = tensor.toString?.() || ''; const m = s.match(/^([a-zA-Z0-9_]+)(?:\[|$)/); if (m) return m[1]; return null; }, () => tensor.type?.dataType, () => tensor.dtype, () => tensor.dataType ]; for (const ex of dtypeExtractors) { try { const r = ex(); if (r) return this._normalizeDtype(r); } catch { continue; } } return 'unknown'; }
    _normalizeDtype(dtype) { if (typeof dtype === 'number') { const map = {1:'float32',6:'int32',9:'bool'}; return map[dtype]||`type_${dtype}`; } if (typeof dtype === 'string') { const n = dtype.toLowerCase().replace(/^dt_/,''); const aliases = {'float':'float32','double':'float64','int':'int32'}; return aliases[n]||n; } return String(dtype); }
    _guessDomain(input) { const shape = this._parseShape(input); const name = input.name?.toLowerCase()||''; if (shape.length===4) { if (shape[1]===3||shape[3]===3) return 'image'; } if (shape.length===2) return 'tabular'; if (shape.length===3) return 'sequence'; if (name.includes('image')||name.includes('pixel')) return 'image'; if (name.includes('text')||name.includes('token')) return 'text'; return 'unknown'; }
    _guessSemantics(output) { const shape = this._parseShape(output); const name = output.name?.toLowerCase()||''; if (name.includes('box')||name.includes('bbox')) return 'bounding_boxes'; if (name.includes('class')||name.includes('label')||name.includes('logit')) return 'classification'; if (name.includes('mask')) return 'segmentation_mask'; if (shape.length===2 && shape[1]<10000) return 'logits'; return 'unknown'; }
    _checkQuantizationWithProvenance(graph) { const quantOps=['QuantizeLinear','DequantizeLinear','Q','DQ']; let isQuantized=false; const found=[]; if (graph.nodes) for (const n of graph.nodes) { const op = n.type||n.op_type; if (quantOps.includes(op)) { isQuantized=true; found.push(op); } } return { isQuantized, precision: isQuantized ? 'int8' : 'fp32', observed: found, provenance: 'graph_scan', confidence: isQuantized ? 0.9 : 1.0 }; }
    _suggestRuntimes(model) { const format=this._detectFormat(model); const runtimes=['cpu']; if (format==='onnx') { runtimes.push('onnxruntime'); if (this._checkQuantizationWithProvenance(model).isQuantized) runtimes.push('qnn'); } return runtimes; }
    _extractMetadata(model) { const m={}; if (model.metadata) { m.producer=model.metadata.producer; m.version=model.metadata.version; m.domain=model.metadata.domain; m.docString=model.metadata.docString; } if (model._metadata) { m.producer=m.producer||model._metadata.producer; m.version=m.version||model._metadata.version; m.domain=m.domain||model._metadata.domain; m.docString=m.docString||model._metadata.description; } if (model.description) m.docString=m.docString||model.description; return m; }
    _estimateComplexity(graph) { let parameters=0,flops=0,size=0; if (graph.nodes) for (const node of graph.nodes) { const op=node.type||node.op_type; if (op==='Conv'||op==='MatMul') { parameters+=1000; flops+=10000; } } return {parameters,flops,size}; }
    _extractUsage(model) { if (model.usage) return model.usage; if (model._metadata && model._metadata.usage) return model._metadata.usage; return 'This model can be used for classification, detection, segmentation.'; }
    _extractApplication(model) { if (model.application) return model.application; if (model._metadata && model._metadata.application) return model._metadata.application; return ['automation','monitoring','analysis']; }
}
